In [19]:
#Entrada Saida de dados e tipos primitivos
#xent = input('insira algo ')
#print('hello '+ xent)
xstring = 'teste'
xint = 23
xfloat = 2.75
xcond = True
print('string '+ xstring)
print('Int '+ str(xint))
print('Float '+ str(xfloat))
print('Cond '+ str(xcond))

#Operacoes
x1 = 3
x2 = 2
print(x1 + x2)
print(x1 - x2)
print(x1 * x2)
print(x1 / x2)
print(x1 ** x2)
print(x1 % x2)

#Listas Tuplas Vetores e Matrizes dicionário
xlist = [1, 2.2, 'abc', [1,2,3]]
print(xlist[1])
print(xlist[:3])
print(xlist[3][2])


xdic ={'x1':2,'x2':'opa'}
print(xdic['x1'])
print(xdic['x2'])

xtup =(1,2,3)
print(xtup[2])

#operadores lógicos e condicionais
varx = 5
if varx == 5:
    print('> '+ str(varx > x2))
    print('< '+ str(varx < x2))
    print('== '+ str(varx == x2))
    print('!= '+ str(varx != x2))
elif varx != 5:
    print('Elif')
else:
    print('Else')

#lacos de repetição
listLaco = [1,2,3]
for ls in listLaco:
    print('Laço for ' + str(ls))

for le in range(0,5):
    print('Laço range '+ str(le))

i = 0
while i < 5:
    print('Laço while {}'.format(i))
    i = i + 1

#List Compreension
x = [1,2,3,4]
[item**2 for item in x]

#Funcoes
def potenciacao(x):
    return x**2

print('func {}'.format(potenciacao(4)))

#lambda map filter
xw=[1,2,3,4,5,6]
print(list(map(lambda x:x**3, xw)))

print(list(filter(lambda x: x%2 == 0, xw)))


string teste
Int 23
Float 2.75
Cond True
5
1
6
1.5
9
1
2.2
[1, 2.2, 'abc']
3
2
opa
3
> True
< False
== False
!= True
Laço for 1
Laço for 2
Laço for 3
Laço range 0
Laço range 1
Laço range 2
Laço range 3
Laço range 4
Laço while 0
Laço while 1
Laço while 2
Laço while 3
Laço while 4
func 16
[1, 8, 27, 64, 125, 216]
[2, 4, 6]


In [32]:
import numpy as np

minhaLista = [1,2,3]
print('Vetor')
print(np.array(minhaLista))
minhaMatriz = [[1,2,3],[4,5,6],[7,8,9]]
print('Matriz')
print(np.array(minhaMatriz))
print('Arange cria vetores num range')
print(np.arange(0,15,2))
print('Zeros cria vetor de zeros')
print(np.zeros((5,5)))
print('Cria matriz de 1')
print(np.ones((3,3)))
print('Eyes')
print(np.eye(4))
print('Linspace cria vetor com dados espacados')
print(np.linspace(0,15,5))
print('random rand cria vetor de numeros aleatórios ')
print(np.random.rand(3,3,3))
print('random randn cria vetor de num aleatório não uniformes')
print(np.random.randn(4))
print('random randint cria vetor de num aleatorios inteiros')
print(np.random.randint(0,100,6))
print('reshape transforma um vetor em matriz')
arr = np.random.rand(25)
print('Array criado')
print(arr)
arrRes = arr.reshape((5,5))
print('Array transformado')
print(arrRes)
print('Encontra valor min e seu index no array')
print(arrRes.min())
print(arrRes.argmin())
print('Encontra valor max e seu Index no array')
print(arrRes.max())
print(arrRes.argmax())

Vetor
[1 2 3]
Matriz
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Arange cria vetores num range
[ 0  2  4  6  8 10 12 14]
Zeros cria vetor de zeros
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Cria matriz de 1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Eyes
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Linspace cria vetor com dados espacados
[ 0.    3.75  7.5  11.25 15.  ]
random rand cria vetor de numeros aleatórios 
[[[0.64611679 0.44683539 0.76416658]
  [0.66079754 0.57573425 0.4851382 ]
  [0.13008396 0.15286486 0.8499768 ]]

 [[0.90143224 0.09349047 0.82767958]
  [0.74388335 0.74529339 0.52997819]
  [0.68147307 0.22307871 0.4223418 ]]

 [[0.7247182  0.44533218 0.3581137 ]
  [0.83351782 0.17505604 0.85250444]
  [0.65055407 0.88204797 0.94093319]]]
random randn cria vetor de num aleatório não uniformes
[ 1.02412078 -0.78439911  1.4783649  -0.0669573 ]
random randint cria vetor de num aleatorios inteiros
[47  2 57 14 52 25]
reshape transforma um v